### ISSUE TITLE
Review DeGAUSS containerized platforms

### ISSUE THREAD

**Issue by sigmafelix** [Spatiotemporal-Exposures-and-Toxicology/Scalable_GIS#23]
### TODO
- [x] Check if it runs -- runs smoothly on apptainer
- [x] Check its scalability: review the code and run test scripts with 10K+ points
- [ ] Adopt design ideas
- [ ] Include container build-run scripts into Scalable_GIS package

### Points of consideration
- DeGAUSS is a special platform for calculating geomarkers in relatively local areas (i.e., accessibility is evaluated at affiliated medical centers); our target is the mainland US, so the scalability is more important than the existing platform
- They hosted their files on Amazon S3; each container includes minimal base system components and scripts. Our system needs to map the fixed (or parametrized) locations in ddn for reproducibility
- Basic design
    - A text file to read user information for SLURM submission: e-mail, job alias, output and error log file names
    - A container with postscripts that install required packages we often use (i.e., `exactextractr`, `terra`, etc.)
    - A fixed script that includes default arguments, which will make users have no trouble with entering incorrect/invalid arguments in calculation functions

**Comment by sigmafelix** [comment]
This platform will be referred to as an existing solution for local / study-specific geocomputation needs.
